### ISSUE TITLE
[FUTURE] Watch for release of JEP 405 "Future Work" -- specifically: `Deconstruction patterns` to close last syntax gap

### ISSUE THREAD

**Issue by GavinRay97** [Randgalt/expressive-java#3]
https://openjdk.java.net/jeps/405

This should fix that last little bugger:
https://github.com/Randgalt/expressive-java/blob/16a5a15e5ecaca303b2bed830b3c52ec789b40b1/java-17/src/main/java/examples/SimpleInterpreter.java#L74-L79

I think it's worth posting to Reddit/HackerNews to show this off to be honest, it's pretty astonishing. Not sure if it's worth waiting until that JEP is merged, maybe could just make a note of it in a comment or something.

Near the bottom of the page:

![image](https://user-images.githubusercontent.com/26604994/140959823-fffa5dff-7898-452b-a2fc-329f82ed0ac9.png)

**Comment by Randgalt** [comment]
Nice! I can't wait for it.

**Comment by Randgalt** [comment]
> I think it's worth posting to Reddit/HackerNews to show this off to be honest, it's pretty astonishing. 

@GavinRay97 if you don't mind, can you post it? Might be better coming form someone other than me.

**Comment by GavinRay97** [comment]
@Randgalt Sorry for the late reply -- went on vacation, just back.

Yeah no problem, it's definitely worth posting! Just need to try to come up with a succinct title that conveys how impressive it is.

Something like:

```
Expressive Java: Scala interpreter translated to modern Java. As of JDK 17, code nearly identical
```

**Comment by GavinRay97** [comment]
The time is almost nigh:

https://www.reddit.com/r/java/comments/tgdl7y/record_patterns_officially_planned_as_preview/

**Comment by Randgalt** [comment]
yeah - I saw that. good news
